config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  get 'users/index'
  root 'items#index'
  resources :items do
    member do
      get 'confirm'
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :users do
    collection do
      get 'logout'
      get 'deliber_address'
      get 'email_password'
      get 'identify'
      get 'signup'
      get 'users_registration'
    end
  end
  resources :cards, only: [:new, :create, :edit, :update, :show] do
    collection do
      post 'delete', to: 'cards#delete'
    end
    member do
      get 'confirmation'
      get 'buy'
    end
  end
  resources :addresses, only: [:new, :create]
  resources :categories, only: [:new, :create]
  resources :brands, only: [:new, :create]
  resources :images, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable      
  
  has_many :cards 
  has_many :items
  # belongs_to :address, optional: true
  has_many  :addresses
  accepts_nested_attributes_for :addresses
  # バリデーション設定
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d!@#\$%\^\&*\)\(+=._-]{7,128}\z/i
  VALID_KANJI_KANA_KATAKANA_REGEX = /\A[ぁ-んァ-ン一-龥]/
  VALID_KANJI_REGEX = /\A[一-龥]+\z/
  # ふりがな
  VALID_KANA_REGEX = /\A[ぁ-んー－]+\z/
  # 全角ふりがな
  VALID_KANA_FUll_WIDTH = /\A^[ぁ-んァ-ヶー一-龠]+$\z/
  VALID_KATAKANA_REGEX = /\A[\p{katakana}\p{blank}ー－]+\z/
  VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
  VALID_POSTAL_CODE = /\A\d{3}-\d{4}\z/i

  # ＜ユーザー情報：6項目＞
  # ニックネームが必須
  validates :nickname, presence: true, length: {maximum:50}
  # メールアドレスは一意
  validates :email, presence: true, uniqueness:true, length: { maximum:255 }, format: { with: VALID_EMAIL_REGEX, message: 'のフォーマットが不適切です'}

  # - パスワードは必須、7文字以上
  validates :password, presence:true, length: { minimum: 7 }, format: { with: VALID_PASSWORD_REGEX, message:'は英字と数字両方を含むパスワードを設定してください'}
  # パスワードは確認用を含めて2回入力
  # validates :password_confirmation, presence: true, length: { in: 7..128 }, format: { with: VALID_PASSWORD_REGEX, message: 'は英字と数字両方を含むパスワードを設定してください'}

  # <本人確認情報：5項目>
  # - ユーザー本名が、名字と名前でそれぞれ必須
  # - ユーザー本名は全角で(漢字、ひらがな、カタカナ）入力
  validates  :first_name,presence: true ,format: { with: VALID_KANJI_KANA_KATAKANA_REGEX, message:'は全角で入力してください'}
  validates  :second_name,presence: true ,format: { with: VALID_KANJI_KANA_KATAKANA_REGEX, message:'は全角で入力してください'}
  # - ユーザー本名のふりがなが、名字と名前でそれぞれ必須
  validates :hurigana_first, presence: true, length: { maximum: 35 }, format: { with: VALID_KANA_REGEX, message: 'はひらがなで入力して下さい'}
  validates :hurigana_second, presence: true, length: { maximum: 35 }, format: { with: VALID_KANA_REGEX, message: 'はひらがなで入力して下さい'}
  # - ユーザー本名のふりがなが、全角で必須
  validates :hurigana_first, presence: true, format: { with: VALID_KANA_FUll_WIDTH, message:'は全角で入力してください'}
  validates :hurigana_second, presence: true, format: { with: VALID_KANA_FUll_WIDTH, message:'は全角で入力してください'}
  # - 生年月日が必須
  def birthday
    "#{BirthYyyy.find(self.birth_yyyy_id).year}/#{BirthMm.find(self.birth_mm_id).month}/#{BirthDd.find(self.birth_dd_id).day}"
  end
  # - メールアドレスは@とドメインを含む必要がある
  # /^([a-zA-Z0-9])+([a-zA-Z0-9\._-])*@([a-zA-Z0-9_-])+([a-zA-Z0-9\._-]+)+$/
  
  # ＜商品送付先住所情報：6項目必須、2項目任意＞
  # 出品機能作成時に後ほど設定の為一旦保留
  # - 郵便番号が必須
  # validates :postaladdress, presence: true, format: { with: VALID_POSTAL_CODE, message: '郵便番号を入力してください'}
  # - 都道府県が必須
  # validates :Prefectures, presence: true
  # - 市区町村が必須
  # validates :Municipality, presence: true
  
  # - 送付先氏名が必要、名字と名前でそれぞれ必須
  # validates :Destination_name, presence: true
  # validates :first_name_kana, presence: true,format: { with: VALID_KATAKANA_REGEX, message: 'はカタカナで入力して下さい'}
  # validates :second_name_kana, presence: true,format: { with: VALID_KATAKANA_REGEX, message: 'はカタカナで入力して下さい'}

  # - 送付先氏名のふりがなが、名字と名前でそれぞれ必須
  # validates :validates :Destination name, presence: true,

  # - 番地が必須
  # validates :address, presence: true,

  # - マンション名やビル名、そしてその部屋番号は任意の為記載不要

  # - お届け先の電話番号は任意
  # /^\d{11}$/
  # record.errors[:name] << '電話番号は0から始まる必要があります'

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  
  def new
    @user = User.new
    @user.addresses.build
  end

  def create
    @user = User.new(users_params)
    if @user.save
      bypass_sign_in(@user)
      flash[:notice] = "新規会員登録しました."
      redirect_to root_path
      # redirect_to  root_path(@user.id), notice: '新規会員登録完了しました。'
    else
      redirect_to root_path, alert: '新規会員登録に失敗しました。'
    end
    # unless @user.valid?
    #   flash.now[:alert] = @user.errors.full_messages
    #   render :new and return
    # end
    # session["devise.regist_data"] = {user: @user.attributes}
    # session["devise.regist_data"][:user]["password"] = params[:user][:password]
    # @address = @user.build_address
    # render :new_address
  end

  private
  def users_params
    params.require(:user).permit(:nickname,:first_name,:second_name,:email,:password,
                                 :hurigana_first,:hurigana_second,:phone_number,
                                 :birthday_year,:birthday_month,:birthday_day,
                                 addresses_attributes: [:postal_code, :prefectures,:municipalities,:house_number,:room_number,:user_id])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user_blank?, only: [:show, :logout]
  def index
    @users = User.all
  end

  
  def new
    @user = User.new
  end

  def create

    @user = User.new(users_params)
    if @user.save
      redirect_to  users_path(@user.id), notice: '新規会員登録完了しました。'
    else
      redirect_to root_path, alert: '新規会員登録に失敗しました。'
    end

  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  def logout
  end

  def deliber_address
  end

  def email_password
  end

  def identify
  end

  private
  # ユーザーがログインしていなければフロントへ
  def current_user_blank?
    if current_user.blank?
      redirect_to root_path
      flash[:alert] = 'ログインを行なってください。'
    end
  end

  def users_params
    params.require(:user).permit(:nickname,:first_name,:second_name,:email,:password,:hurigana_first,:hurigana_second,:birthday,:phone_number)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_leftbar.html.haml
-# 左側のメニューバー部分
.h_left
  .h_left__contents
    %ul
      %li
        = link_to "マイページ", "/users/show", class: "h_left__contents__link"
      %li
        = link_to "いいね！一覧", "#", class: "h_left__contents__link"
      %li
        = link_to "出品する", "/items/new", class: "h_left__contents__link"
    
  .h_left__text
    設定
  .h_left__contents
    %ul
      %li
        = link_to "支払い方法", confirmation_card_path(current_user.id), class: "h_left__contents__link"
      %li
        = link_to "発送元・お届け先住所変更", "/addresses/new", class: "h_left__contents__link"
      %li
        = link_to "メール/パスワード", "#", class: "h_left__contents__link"
      %li
        = link_to "本人情報", "#", class: "h_left__contents__link"
      %li
        = link_to "ログアウト", "/users/logout", class: "h_left__contents__link"

app/views/users/_user-signup.html.haml
= render "items/items_header"
-# 上記ヘッダー箇所

.m_single-container
  .m_single-main
    .m_l-single-container
      %h2.m_l-single-head__registration 新規会員登録
    .m_l-single-inne__registration-form
      .m_l-single-content
        =link_to "メールアドレスで登録する", "/users/sign_up",class: "m_registration"
        %i.m_icon-mail
        .m_heder__login-accout__facebook
          %input.m_login-btn__facebook{style:  "", type: "button", value: "Facebookで登録する"}/
        .m_heder__login-account__google
          %input.m_login-btn__google{style: "", type: "button", value: "Googleで登録する"}/
.m_footer
=render "items/items_footer"

app/views/users/_users_header2.html.haml
-# パンくず部分

= render "items/items_toppage_header"

.h_head
  %ul
    %li
      = link_to "メルカリ", "#", class:"h_head--color"
    %li
      = image_tag '矢印アイコン　右4.png', class: 'h_head__icon'
    %li
      マイページ

app/views/users/index.html.haml
%h1 Users#index
%p Find me in app/views/users/index.html.haml

app/views/users/logout.html.haml
.all
  = render "users_header2" 
  .h_main
    = render "leftbar"
    .i_right
      .i_logoutMenu
        %form{:action => "/users/show", :method => "post", :novalidate => "novalidate", :class => "i_logoutInner"}
          .i_single-content
            %button{:type => "submit",class:"i_logoutBtn",method: "delete"}
              = link_to "ログアウト",destroy_user_session_path,class: "i_logoutBtn", method: "delete"
  = render "items/items_toppage_footer"

app/views/users/new.html.haml
= render "users/new-users"

app/views/users/show.html.haml
-# マイページの実装
.all
  = render "users_header2" 

  .h_main
    = render "leftbar"

    .h_right
      .h_top
        = image_tag 'orange0024.png', class: 'h_top--size'
        .h_top__icon
          = image_tag 'member_photo_noimage_thumb.png', class: 'h_top__icon--size'
          .h_top__icon__name
            = current_user.nickname
      .h_items
        - current_user.items.each do |item|
          - if item.images[0].present?
            %ul
              %li
                = link_to image_tag(item.images[0].image.url, height: "150", width: "150", class: "h_items_img"), item_path(item.id)
              %li
                = link_to item.nickname, item_path(item.id), {class: "h_items_name"}


  = render "items/items_toppage_footer"

  

app/views/users/signup.html.haml
= render "users/user-signup"

app/views/users/users_registration.html.haml
= render "items/items_header"
.t_main
  .t_credit
    会員情報入力
  .t_credit_area
    .t_single_content
      .t_names_form__group
        .t_names_member
          .t_names_number
            ニックネーム
          .t_names_hissu
            必須
        = form_tag('/items/new',method: :post) do
          %input{type: "input",class: "t_names_input",placeholder: "例)メルカリ太郎"}
      .t_names_form__group
        .t_names_member
          .t_names_number
            メールアドレス
          .t_names_hissu
            必須
        = form_tag('/items/new',method: :post) do
          %input{type: "input",class: "t_names_input",placeholder: "例)PC・携帯どちらでも可"}
      .t_names_form_password
        .t_names_member
          .t_names_number
            パスワード
          .t_names_hissu
            必須
        = form_tag('/items/new',method: :post) do
          %input{type: "input",class: "t_names_input",placeholder: "7文字以上の半角英数字"}
          -# .t_password_error エラーメッセージ
          -#   パスワードを入力して下さい 
          .t_password_view
            ※ 英字と数字の両方を含めて設定してください
          %input{type: "checkbox",class:"t_password_check"}
            %label{class: "t_pass"} パスワードを表示する
      .t_user
        本人確認
      .t_confirm_user
        安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
      .t_names_form__group1
        .t_names_member
          .t_names_number
            お名前
          .t_names_hissu
            必須
        = form_tag('/items/new',method: :post) do
          %input{type: "input",class: "t_names_input",placeholder: "例)山田"}
        = form_tag('/items/new',method: :post) do
          %input{type: "input",class: "t_names_input",placeholder: "例)彩"}  
      .t_names_form__group2
        .t_names_member
          .t_names_number
            お名前かな
          .t_names_hissu
            必須
        = form_tag('/items/new',method: :post) do
          %input{type: "input",class: "t_names_input",placeholder: "例)やまだ"}
        = form_tag('/items/new',method: :post) do
          %input{type: "input",class: "t_names_input",placeholder: "例)あや"}
      .t_cards_form__group2
        .t_cards_member
          .t_cards_limit
            生年月日
          .t_cards_hissu
            必須
        .t_pulldown
          .t_pulldown_group
            = form_tag('/items/new',method: :post) do
              %select(name="example" class="t_pulldown_group__menu")
                %option 1999
                %option 2000
                %option 2003
                %option 2004
                %option 2005
                %option 2006
                %option 2007
                %option 2008
                %option 2009
                %option 2010
                %option 2011
                %option 2012
            %span(class = "t_span1")  年
          .t_30years_group
            = form_tag('/items/new',method: :post) do
              %select(name="example" class="t_pulldown_group__menu")
                %option 1
                %option 2
                %option 3
                %option 4
                %option 5
                %option 6
                %option 7
                %option 8
                %option 9
                %option 10
                %option 11
                %option 12     
            %span(class = "t_span2")  月
          .t_30years_group
            = form_tag('/items/new',method: :post) do
              %select(name="day" class="t_pulldown_group__menu")
                %option 20
                %option 21
                %option 22
                %option 23
                %option 24
                %option 25
                %option 26
                %option 27
                %option 28
                %option 29
                %option 30
                %option 31     
            %span(class = "t_span2")  日
      .t_users_identify
        ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
      .t_next
        「次へ進む」のボタンを押すことにより,
        %span(class = "t_kiyaku") 利用規約
        に同意したものとみなします。
      %input{type:"button",class: "t_btn",value: "次へ進む"}
=render "items/items_footer"