config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  get 'users/index'
  root 'items#index'
  resources :items do
    member do
      get 'confirm'
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :users do
    collection do
      get 'logout'
      get 'deliber_address'
      get 'email_password'
      get 'identify'
      get 'signup'
      get 'users_registration'
    end
  end
  resources :cards, only: [:new, :create, :edit, :update, :show] do
    collection do
      post 'delete', to: 'cards#delete'
    end
    member do
      get 'confirmation'
      get 'buy'
    end
  end
  resources :addresses, only: [:new, :create]
  resources :categories, only: [:new, :create]
  resources :brands, only: [:new, :create]
  resources :images, only: [:new, :create]
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user, optional: true
  belongs_to :brand, optional: true
  belongs_to :category, optional: true
  has_many :images, dependent: :destroy
  validates :nickname, presence: true
  validates :description, presence: true
  validates :status, presence: true
  validates :shipping_charges, presence: true
  validates :area, presence: true
  validates :days, presence: true
  validates :category, presence: true
  validates :price, presence: true
  accepts_nested_attributes_for :images,allow_destroy: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show,:destroy, :edit, :update]
  def index
    @item = Item.all
    @items = Item.order("created_at DESC").limit(3)
    @random = Item.order("RAND()").limit(3)
    @categories = Category.all
    @present = Category.where(ancestry: nil)
  end
  
  def new
    if current_user.blank?
    redirect_to root_path
    flash[:alert] = 'ログインを行なってください。'
    else
      @item = Item.new
      @item.images.new
      @category = Category.roots
      @category_parent_array = ["指定なし"]
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
      end
      @item.images.build
    end
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find(params[:parent_name]).children
  end

  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def create
    @item = Item.new(items_params)
    if @item.save(items_params)
      redirect_to  items_path(@item.id), notice: 'アイテムを出品しました。'
    else
      redirect_to "/items/new", alert: 'アイテムの出品に失敗しました。'
    end
  end

  def show
    if current_user.blank?
      @user = 0
    else
      @item = Item.find(params[:id])
    end
  end

  def edit
    if current_user.blank?
      redirect_to root_path
      flash[:alert] = 'ログインを行なってください。'
    else
      if @item.user.id == current_user.id
      @category = Category.roots
      @category_parent_array = ["指定なし"]
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
      end
      else
        redirect_to root_path , notice: '自身の出品ではないため編集できません'
      end
    end
  end

  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find(params[:parent_name]).children
  end

  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find(params[:child_id]).children
  end


  def update
    id = params[:item][:category_id].to_i
    if id >= 22 && 92 >= id || id >= 106 && 154 >= id || id >= 162 && 185 >= id || id >= 193 && 217 >= id || id >= 223 && 239 >= id || id >= 244 && 248 >= id || id >= 253 && 258 >= id || id >= 263 && 268 >= id || id >= 273 && 280 >= id || id >= 285 && 290 >= id
      if @item.update(items_params)
        redirect_to root_path , notice: 'アイテムの情報を編集しました。'
      else
        render :edit, alert: 'アイテムの情報の編集に失敗しました。'
      end
    else
      redirect_to edit_item_path(@item.id) , alert: 'カテゴリーの選択を行なってください。'
    end
  end

  def destroy
    if @item.user.id == current_user.id
    @item.destroy
    redirect_to root_path
    flash[:alert] = '削除しました。'    
    else
      redirect_to root_path , notice: '自身の出品ではないため削除できません'
    end
  end

  def confirm
    if current_user.blank?
      redirect_to root_path
      flash[:alert] = 'ログインを行なってください。'
    else
      @card = current_user.cards.first
      if @card.present?
        customer = Payjp::Customer.retrieve(@card.customer_id)
        @default_card_information = customer.cards.retrieve(@card.card_id)
      end
      @item = Item.find(params[:id])
      if @item.soldout == 1
        redirect_to item_path(@item.id)
        flash[:alert] = '既に購入されています'
      elsif current_user.id == @item.user_id
        redirect_to item_path(@item.id)
        flash[:alert] = '出品者の為、購入できません'
      end
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def items_params
# ここを編集する
    params.require(:item).permit(:nickname,:description,:category_id, :status,:shipping_charges,:area,:days,:price,images_attributes: [:image,:id,:_destroy]).merge(user_id: current_user.id)
  end

  # payjpを使用するためのメソッド
  def get_payjp_info 
    if Rails.env == 'development'
      Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
    else
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_ACCESS_KEY]
    end
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_aaa.html.haml
.i_main
  .i_mainscreen
    .i_content
      .i_content__top
        -# 以下から商品の詳細
        .i_item
          .i_item__name
            カルボナーラ
          .i_item__body
            %ul.gazou
              %li.gazou_1
                = image_tag str="/assets/food_spaghetti_carbonara.png" 
                %ul.gazou_mini
                  %li.gazou_mini1
                    = image_tag str="/assets/food_spaghetti_carbonara.png" ,size:"75x75"
                  %li.gazou_mini2
                    = image_tag str="/assets/food_spaghetti_carbonara.png" ,size:"75x75"
                  %li.gazou_mini3
                    = image_tag str="/assets/food_spaghetti_carbonara.png" ,size:"75x75"
          .i_item__price
            %span ¥2000
            .i_item__price-detail
              %span (税込)
              %span 送料込み
          .i_itemDetail
            親譲りの無鉄砲で小供の時から損ばかりしている。小学校に居る時分学校の二階から飛び降りて一週間ほど腰を抜かした事がある。なぜそんな無闇をしたと聞く人があるかも知れぬ。別段深い理由でもない。新築の二階から首を出していたら、同級生の一人が冗談に、いくら威張っても、そこから飛び降りる事は出来まい。弱虫やーい。と囃したからである。小使に負ぶさって帰って来た時、おやじが大きな眼をして二階ぐらいから飛び降りて腰
          -# 以下から表の作成
          .i_table
            %table
              %tr
                %th 出品者
                %td hage
              %tr
                %th カテゴリー
                %td 
                  = link_to items_path do
                    メンズ
                  %br
                  = link_to items_path do
                    ジャケット/アウター
                  %br
                  = link_to items_path do
                    ノーカラージャケット
              %tr
                %th ブランド
                %td 
              %tr
                %th 商品のサイズ
                %td 
              %tr
                %th 商品の状態
                %td 新品/未使用
              %tr
                %th 配送料の負担
                %td 着払い（購入者負担）
              %tr
                %th 配送元の地域
                %td 
                  = link_to items_path do
                    大阪府
              %tr
                %th 発送日の目安
                %td 2~3日で発送
          -# 以下からオプションボタン
          .i_option
            %ul
              %li.i_option__btn
                %i.fas.fa-star
                お気に入り０
            %ul.i_option__fav
              %li.i_option__fav__btn
                = link_to items_path do
                  %i.fa.fa-flag
                    不適切な商品の通報
          -# 以下からコメントフォーム
        .i_commentBox
          %ul.i_commentContents
            = form_tag('/items/show',method: :post)do
              %textarea(name="commentarea" rows="5" class="i_input_comment_area")
              %p.i_noticeMsg
                相手のことを考え丁寧なコメントコメントを心がけましょう。
                %br
                不快な言葉遣いなどは利用制限や退会処分となることがあります。
              %button(name="button" type="submit" class="i_commentBtn")
                %i.fas.fa-comment 
                コメントする
          -# 以下からリンク
      %ul.i_main__links
        %li
          = link_to items_path do
            %i.fa.fa-angle-left
            %span
            前の商品
        %li
          = link_to items_path do
            %span
              後の商品
            %i.fa.fa-angle-right
      .i_main__relateditem
        = link_to items_path do
          メンズをもっと見る
    -# 以下からフッター
.i_footer
  %ul.i_contents
    .i_content
      %h.i_content_head
    .i_footer_logo
      = link_to items_path do
        = image_tag str="/assets/logo-white.png" ,size:"160x46"

app/views/items/_items_edit.html.haml
= render "items_header"
.t_all
  .t_form_action
    = form_with model: @item, local: true do |f|
      .t_display
        .t_display__formgroup 
          .t_display_name
            .t_display_name__junle
              出品画像
            .t_display_name__hissu
              必須
          .t_display_names
            最大5枚までアップロードできます
          .t_sell_uploader
            .t_sell_uploader__form
              .t_image_field
                #previews_edit
                  .t_edit_input
                    = f.fields_for :images do |img|
                      %ul.bbb{data:{index: img.index},id: "t_input_type"}
                        %li
                          = image_tag img.object.image.url,data: { index: img.index }, width: "124", height: '123', id: img.index, class: "js-file_group"
                        %li.botton_edit                      
                          = img.file_field :image, type: 'file',value:"", data: { index: img.index } ,style: "display:none" ,class: "js-file", name: "item[images_attributes][#{img.index}][image]"
                          %label.t_bbb_edit{for: "item_images_attributes_#{img.index}_image"}
                            %span{class: "t_input-file"} 編集
                          .delete{id: img.index, data:{index: img.index}} 削除
                          .t_input-file{id: img.index ,style: "display:none"}
                        - if @item.persisted?
                          = img.check_box :_destroy, data:{ index: img.index }, class: 'hidden-destroy'
                    - if @item.images.count < 5
                      = file_field_tag :image, type: 'file',name: "item[images_attributes][#{@item.images.count}][image]",style: "display:none" ,class: "img_count",id: "file#{@item.images.count}"
                    - if @item.images.count < 5
                      %label.t_input-file_edit 
                        %span ファイルを選択

      .t_items
        .t_items__name
          .t_items_names
            .t_items_names__items
              商品名
            .t_items_names__hissu
              必須
          .t_form_style
            = f.text_field :nickname,class: "t_input_text_field",placeholder:"40文字まで"
        .t_items_explanation
          .t_items_explanation__form
            .t_explanation_items
              商品の説明
            .t_explanation_hissu
              必須
          = f.text_area :description,class: "t_input_text_field2",placeholder:"商品の説明（必須 1,000文字以内)"
      .t_three 
        .t_three__details
          商品の詳細
        .t_category
          .t_category_group
            .t_category_name_group
              .t_category_name_group__category
                = f.label 'カテゴリー', class: 'listing-default__label'
              .t_category_name_group__hissu
                必須
            .t_items_name__items
              .t_category-select
                = f.collection_select :category_id, Category.roots, :id, :name, id: 'category'
                .listing-product-detail__category
              .t_status
                .t_status_group
                  .t_status_group__status
                    商品の状態
                  .t_status_group__hissu
                    必須
                .t_status_style
                  =f.select :status,
                    [["選択してください"],
                    ["新品,未使用"],
                    ["未使用に近い"],
                    ["目立った汚れなし"],
                    ["傷や汚れあり"],
                    ["未使用に近い"],
                    ["全体的に状態が悪い"]],{},{class: "t_status_select_form"}
      .t_four
        .t_four__delivery
          配送について
        .t_delivery_group
          .t_delivery_group__delivery
            配送料の負担
          .t_delivery_group__hissu
            必須
        .t_items_name__items
          .t_form_style_delivery
            = f.select :shipping_charges,
              [["選択してください"],
              ["送料込み(出品者負担)"],
              ["着払い(購入者負担)"]],{},{class: "t_delivery_form"}
        .t_area_group
          .t_area_group__area
            配送元の地域
          .t_delivery_group__hissu
            必須
        .t_items_name__items
          .t_form_style_delivery
            = f.collection_select :area, Prefecture.all, :area, :area,{},{class: "t_delivery_form"} 
        .t_days_group
          .t_days_group__days
            発送までの日数
          .t_delivery_group__hissu
            必須
        .t_items_name__items
          .t_form_style_delivery
            = f.select :days,
              [["選択してください"],
              ["1〜2日で発送"],
              ["2〜3日で発送"],
              ["4〜7日で発送"]],{},{class: "t_delivery_form"}                            
      .t_five
        .t_five__price
          価格（¥300〜9,999,999）
        .t_five__selling_price
          .t_selling_price_group
            .t_selling_price_group__price
              販売価格
            .t_selling_price_group__hissu
              必須
          .t_yen
            ¥
          .t_number_form
            = f.number_field :price ,class: "t_number_form", style: "text-align: right"
        .t_form_error_number
        .t_bottun_form
          = f.button "編集する",class: "t_bottun_form__display", style: "t_bottun_form__display"
          .t_bottun_form__back
            = link_to "もどる", "/items", class: "t_bottun_form__back"
= render "items_footer"

app/views/items/_items_footer.html.haml
.h_footer
  %ul
    .h_footer__clearfix
  = link_to image_tag("logo-white.png", class: "h_footer__logo"), "#"

app/views/items/_items_header.html.haml
.h_header
  = link_to image_tag("logo.png", class: "h_header__logo"), root_path

app/views/items/_items_show.html.haml
.i_main
  .i_mainscreen
    .i_content
      .i_content__top
        -# 以下から商品の詳細
        .i_item
          .i_item__name
            =@item.nickname
          .i_item__body
            .gazou
              .gazou_1
                = image_tag @item.images[0].image.url, width: "560"
                .gazou_mini
                  - @item.images.each_with_index do |image, i|
                    .gazou_mini1
                    = image_tag image.image.url, data: { index: i },size:"75x75"
          .i_item__price
            %span 
              ¥
              =@item.price
            .i_item__price-detail
              %span (税込)
              %span 送料込み
          .i_itemDetail
            = @item.description
          -# 以下から表の作成
          .i_table
            %table
              %tr
                %th 出品者
                %td 
                  = @item.user.nickname
              %tr
                %th カテゴリー
                %td 
                  = link_to items_path do
                    = @item.category.root.name
                    %p/
                    = @item.category.parent.name
                    %p/
                    = @item.category.name
              %tr
                %th 商品の状態
                %td 
                  =@item.status
              %tr
                %th 配送料の負担
                %td 着払い（購入者負担）
              %tr
                %th 配送元の地域
                %td 
                  = link_to items_path do
                    =@item.area
              %tr
                %th 発送日の目安
                %td 
                  =@item.days
          -# 以下からオプションボタン
          .i_option
            %ul
              %li.i_option__btn
                %i.fas.fa-star
                お気に入り０
            %ul.i_option__fav
              %li.i_option__fav__btn
                = link_to items_path do
                  %i.fa.fa-flag
                    不適切な商品の通報
        -# 以下から購入するボタン
        .i_optionMenu
          .i_item-optionBtn
            .i_item-editBtn
              -if @user == 0
                .i_item-editBtn-soldout
              -else
                -if @item.soldout == 1
                  .i_item-editBtn-soldout SoldOut
                -elsif current_user.id == @item.user_id
                  = link_to "編集", edit_item_path(@item),class:"i_item-editBtn-buy" 
                  = link_to "削除", item_path(@item),class:"i_item-deleteBtn",method: :delete, data:{ confirm: '本当に削除しますか?'}
                -elsif @item.soldout == 0
                  = link_to "購入", confirm_item_path(@item),class:"i_item-editBtn-buy" 
          -# 以下からコメントフォーム
        .i_commentBox
          %ul.i_commentContents
            = form_tag('/items/show',method: :post)do
              %textarea(name="commentarea" rows="5" class="i_input_comment_area")
              %p.i_noticeMsg
                相手のことを考え丁寧なコメントコメントを心がけましょう。
                %br
                不快な言葉遣いなどは利用制限や退会処分となることがあります。
              %button(name="button" type="submit" class="i_commentBtn")
                %i.fas.fa-comment 
                コメントする
          -# 以下からリンク
      %ul.i_main__links
        %li
          = link_to items_path do
            %i.fa.fa-angle-left
            %span
            前の商品
        %li
          = link_to items_path do
            %span
              後の商品
            %i.fa.fa-angle-right
      .i_main__relateditem
        = link_to items_path do
          メンズをもっと見る
    -# 以下からフッター
= render "items/items_toppage_footer"

app/views/items/_items_toppage_footer.html.haml
.i_footer
  %ul.i_contents
    .i_content
      %ul
        %h2 
          = link_to "FURIMAについて", "#" ,class: "i_content__head"
        %li
          = link_to "会社概要（運営会社）", "#" ,class: "i_content__list"
        %li
          = link_to "プライバシーポリシー", "#" ,class: "i_content__list"
        %li
          = link_to "FURIMA利用規約", "#" ,class: "i_content__list"
        %li
          = link_to "ポイントに関する特約", "#" ,class: "i_content__list"
      %ul
        %h2
          = link_to "FURIMAについて", "#" ,class: "i_content__head"
        %li
          = link_to "カテゴリー一覧", "#" ,class: "i_content__list"
        %li
          = link_to "ブランド一覧", "#" ,class: "i_content__list"
      %ul
        %h2
          = link_to "FURIMAについて", "#" ,class: "i_content__head"
        %li
          = link_to "FURIMAガイド", "#" ,class: "i_content__list"
        %li
          = link_to "FURIMAロゴ利用ガイドライン", "#" ,class: "i_content__list"
        %li
          = link_to "お知らせ", "#" ,class: "i_content__list"
    .i_footer_logo
      = link_to items_path do
        = image_tag "logo-white.png" ,size:"160x46"

app/views/items/_items_toppage_header.html.haml
.k_head
  .k_head__inner
    .k_head__inner__top
      .k_head__inner__top__logo
        =link_to image_tag("logo.png",class: "k_head__inner__top__logo--size"), root_path
      %input{type: "text-area",placeholder:"キーワードから探す",class: "k_head__inner__top__searchbox"}
      %form{action: "#"}
        %input{type: "submit", name: "submit", value: "", class: "k_head__inner__top__submit"}
      =image_tag "icon-search 1.png",class: "k_head__inner__top__logo2"
    .k_head__inner__bottom
      .k_head__inner__bottom__links
        = link_to "カテゴリー","#", class: "k_head__inner__bottom__links__catBtn"
        = link_to "ブランド","#"
      .k_head__inner__bottom__links

        - if user_signed_in?
          = link_to current_user.nickname,"users/show", class: "k_head__inner__bottom__links"
          = link_to "ログアウト",destroy_user_session_path, method: "delete"
        - else
          = link_to "ログイン","/users/sign_in"
          = link_to "新規会員登録","/users/signup", class: "k_head__inner__bottom__links__newBtn"

app/views/items/_new-items.html.haml
= render "items_header"
.t_all
  .t_form_action  
    = form_with model: @item, local: true do |f|
      .t_display
        .t_display__formgroup 
          .t_display_name
            .t_display_name__junle
              出品画像
            .t_display_name__hissu
              必須
          .t_display_names
            最大5枚までアップロードできます
          .t_sell_uploader
            .t_sell_uploader__form              
              .t_image_field                
                #previews
                  = f.fields_for :images do |i|
                    - if i.index == 0
                      .item-num-0{id: "image-box__container"}
                        = i.file_field :image, type: 'file', name: "item[images_attributes][][image]", value:"", style: "display:none", id:"img-file"
                        %label{for: "img-file"}
                          %span{class: "t_input-file"} ファイルを選択
              .t_icon_camera
              .t_text_drag_drop
      .t_items
        .t_items__name
          .t_items_names
            .t_items_names__items
              商品名
            .t_items_names__hissu
              必須
          .t_form_style
            = f.text_field :nickname,class: "t_input_text_field",placeholder:"40文字まで"
        .t_items_explanation
          .t_items_explanation__form
            .t_explanation_items
              商品の説明
            .t_explanation_hissu
              必須

          = f.text_area :description,class: "t_input_text_field2",placeholder:"商品の説明（必須 1,000文字以内)"              
      .t_three 
        .t_three__details
          商品の詳細
        .t_category
          .t_category_group
            .t_category_name_group
              .t_category_name_group__category
                = f.label 'カテゴリー', class: 'listing-default__label'
              .t_category_name_group__hissu
                必須
            .t_items_name__items
              .t_category-select
                = f.collection_select :category_id, @category, :id, :name, id: 'category'
                .listing-product-detail__category
              .t_status
                .t_status_group
                  .t_status_group__status
                    商品の状態
                  .t_status_group__hissu
                    必須
                .t_status_style
                  =f.select :status,
                    [["選択してください"],
                    ["新品,未使用"],
                    ["未使用に近い"],
                    ["目立った汚れなし"],
                    ["傷や汚れあり"],
                    ["未使用に近い"],
                    ["全体的に状態が悪い"]],{},{class: "t_status_select_form"}

      .t_four
        .t_four__delivery
          配送について
        .t_delivery_group
          .t_delivery_group__delivery
            配送料の負担
          .t_delivery_group__hissu
            必須
        .t_items_name__items
          .t_form_style_delivery
            = f.select :shipping_charges,
              [["選択してください"],
              ["送料込み(出品者負担)"],
              ["着払い(購入者負担)"]],{},{class: "t_delivery_form"}       
        .t_area_group
          .t_area_group__area
            配送元の地域
          .t_delivery_group__hissu
            必須
        .t_items_name__items
          .t_form_style_delivery
            = f.collection_select :area, Prefecture.all, :area, :area,{},{class: "t_delivery_form"} 
        .t_days_group
          .t_days_group__days
            発送までの日数
          .t_delivery_group__hissu
            必須
        .t_items_name__items
          .t_form_style_delivery  
            = f.select :days,
              [["選択してください"],
              ["1〜2日で発送"],
              ["2〜3日で発送"],
              ["4〜7日で発送"]],{},{class: "t_delivery_form"}                            
      .t_five
        .t_five__price
          価格（¥300〜9,999,999）
        .t_five__selling_price
          .t_selling_price_group
            .t_selling_price_group__price
              販売価格
            .t_selling_price_group__hissu
              必須
          .t_yen
            ¥
          .t_number_form
            = f.number_field :price ,class: "t_number_form", style: "text-align: right"          
        .t_bottun_form

          = f.button "出品する",class: "t_bottun_form__display", style: "t_bottun_form__display" 
          .t_bottun_form__back
            = link_to "もどる", "/items", class: "t_bottun_form__back"      
  = render "items_footer"

app/views/items/confirm.html.haml
.h_all
  = render "items_header"
  .h_main
    .h_container
      .h_head
        購入内容の確認
      .h_middle
        .h_middle__box
          .h_middle__box__img
            = image_tag @item.images[0].image.url, class: 'h_middle__box__img'
          .h_middle__box__text
            .h_middle__box__text__goods
              = @item.nickname
            .h_middle__box__text__detail
              .h_middle__box__text__detail__price
              = @item.price
              (税込)　
              .h_middle__box__text__detail__shipping
                送料込み
      .h_foot
        .h_foot__inner
          .h_foot__inner__table
            .h_foot__inner__table__text
              支払金額
            .h_foot__inner__table__price
              ¥
              = @item.price
          .h_foot__inner__point
            %input{type: "checkbox", name: "point", value: "送信", class: "h_foot__inner__point__btn"}
            ポイントを使用 (所持ポイント: P0)
          .h_foot__inner__method 
            支払方法
            -if @card.nil?
              .h_foot__inner__method__form
                = link_to "+登録してください", confirmation_card_path(current_user.id), class: "h_foot__inner__method__form__link"
            -else
              .h_foot__inner__method__pay
                = render "cards/show"
          .h_foot__inner__btn
            %form{action: buy_card_path(@item.id)}
              %input{type: "submit", value: "購入する", class: "h_foot__inner__btn__submit"}

  = render "items_footer"

app/views/items/edit.html.haml
= render "items/items_edit"

app/views/items/index.html.haml
.wrapper 
  = render "toppage"

app/views/items/new.html.haml
= render "items/new-items"

app/views/items/show.html.haml
= render "items/items_show"