config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  get 'users/index'
  root 'items#index'
  resources :items do
    member do
      get 'confirm'
    end
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  resources :users do
    collection do
      get 'logout'
      get 'deliber_address'
      get 'email_password'
      get 'identify'
      get 'signup'
      get 'users_registration'
    end
  end
  resources :cards, only: [:new, :create, :edit, :update, :show] do
    collection do
      post 'delete', to: 'cards#delete'
    end
    member do
      get 'confirmation'
      get 'buy'
    end
  end
  resources :addresses, only: [:new, :create]
  resources :categories, only: [:new, :create]
  resources :brands, only: [:new, :create]
  resources :images, only: [:new, :create]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  
  validates :customer_id, presence: true
  validates :card_id, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :current_user_blank?
  before_action :get_payjp_info, only: [:create, :delete, :show, :buy]

  def edit
  end

  def create
    if params['payjp-token'].blank? #カードにデータが入っていないなら
      redirect_to action: "edit", id: current_user.id
    else
      customer = Payjp::Customer.create( #payjpAPIにクレジットカード情報を登録する記述
      email: current_user.email, 
      card: params['payjp-token'],
      metadata: {user_id: current_user.id} 
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card) 
      if @card.save
        redirect_to card_path(current_user)
      else
        redirect_to action: "edit", id: current_user.id
      end
    end
  end

  def delete
    card = current_user.cards.first #ログインユーザーのカードテーブルの最初の要素を取り出す
    if card.present? #カードにデータが入っているなら
      customer = Payjp::Customer.retrieve(card.customer_id) #顧客情報の取得
      customer.delete
      card.delete
    else
      redirect_to user_path(current_user)
    end
  end

  def show
    card = current_user.cards.first
    if card.present?
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    else
      redirect_to controller: :user, action: "users", id: current_user.id
    end
  end

  def confirmation
    card = current_user.cards 
    redirect_to action: "show"if card.exists?
  end

  def buy
    card = current_user.cards 
    # address = current_user.address
    @item = Item.find(params[:id])
    if @item.soldout == 1
      redirect_to item_path(@item.id)
      flash[:alert] = '既に購入されています。'
    elsif card.blank?
      redirect_to action: "edit", id: current_user.id
      flash[:alert] = '購入にはクレジットカード登録が必要です'
    elsif current_user.id == @item.user_id
      redirect_to item_path(@item.id)
      flash[:alert] = '出品者の為、購入できません'
    else
      card = current_user.cards.first
      charge = Payjp::Charge.create(
        amount: @item.price,
        customer: card.customer_id,
        currency: 'jpy',
      )
      if @item.update(soldout: 1)
        flash[:alert] = '購入しました。'
        redirect_to controller: "users", action: 'show', id:current_user.id
      else
        flash[:alert] = '購入に失敗しました。'
        redirect_to controller: "users", action: 'show', id:current_user.id
      end
    end
  end

  private


  def get_payjp_info
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_ACCESS_KEY]
  end
# ユーザーがログインしていなければフロントへ
  def current_user_blank?
    if current_user.blank?
      redirect_to root_path
      flash[:alert] = 'ログインを行なってください。'
    end
  end
# PAYJPを使用できるように
  # def get_payjp_info
  #   if Rails.env == 'development'
  #     Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
  #   else
  #     Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_ACCESS_KEY]
  #   end
  # end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_show.html.haml
//カード詳細画面の部分テンプレート
.h_ContentsInfo
  .h_ContentsInfo__title
    クレジットカード情報
  .h_ContentsInfo__img
    = image_tag("Visa.png", class: "h_ContentsInfo__img--size")
  .h_ContentsInfo__number
    = "**** **** **** " + @default_card_information.last4
  .h_ContentsInfo__date
    - exp_month = @default_card_information.exp_month.to_s
    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
    = exp_month + " / " + exp_year

app/views/cards/confirmation.html.haml
.all
  = render "users/users_header2"
  .h_main
    = render "users/leftbar"
    .h_right
      .h_right__contents
        %h2.h_right__contents__head 支払い方法
        .h_right__contents__main
          .h_right__contents__main__card
            = link_to edit_card_path(current_user), class: "h_right__contents__main__card__btn", data: {"turbolinks" => false} do
              %i
              = icon('fas', 'credit-card', class: "card__icon")
              クレジットカードを追加する

  = render "items/items_toppage_footer"

app/views/cards/edit.html.haml
.all
  = render "users/users_header2" 
  .h_main
    = render "users/leftbar"
    .main__content
      %section.chapter__container
        %h2.chapter__head クレジットカード情報入力
        = form_tag('/cards', method: :post, action: "create", id: 'charge-form',  name: "inputForm", class: "chapter__container__inner") do
          .form__main__container
            .form__content
              .form__contentgroup
                .form_cards_member
                  %label.payment__card カード番号
                  %span.require__form 必須
                = text_field_tag "number", "", class: "number_input__deafult", placeholder: "半角数字のみ" ,maxlength:"16", type: "text", id: "card_number"
                = image_tag("card-1.gif",class: "icon_card")
              .card__list
                .card__list__picture
                  %label.payment__card 
                    有効期限
                  %span.require__form 
                    必須
                .select__box.top__margin
                  .select__box__half
                    %select.select__default#exp_month{name: "exp_month", type: "text"}
                      %option{value: ""} --
                      %option{value: "1"}01
                      %option{value: "2"}02
                      %option{value: "3"}03
                      %option{value: "4"}04
                      %option{value: "5"}05
                      %option{value: "6"}06
                      %option{value: "7"}07
                      %option{value: "8"}08
                      %option{value: "9"}09
                      %option{value: "10"}10
                      %option{value: "11"}11
                      %option{value: "12"}12
                    -# %i
                    -#   = icon('fas', 'chevron-down')
                    %span.span_month 月
                  .select__box__half
                    -# .icon
                    %select.select__default#exp_year{name: "exp_year", type: "text"}
                      %option{value: ""} --
                      %option{value: "2019"}19
                      %option{value: "2020"}20
                      %option{value: "2021"}21
                      %option{value: "2022"}22
                      %option{value: "2023"}23
                      %option{value: "2024"}24
                      %option{value: "2025"}25
                      %option{value: "2026"}26
                      %option{value: "2027"}27
                      %option{value: "2028"}28
                      %option{value: "2029"}29
                    -# %i
                    -#   = icon('fas', 'chevron-down')
                    %span.span_month 年
              .form__content.top__margin
                .cards_member
                  %label.code セキュリティーコード
                  %span.require__form 必須
                = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
              .single__code
                #card_token
                  = submit_tag "追加する", id: "token_submit", class: "top__margin"
  = render "items/items_toppage_footer"

app/views/cards/new.html.haml
.all
  = render "users/users_header2" 
  .h_main
    = render "users/leftbar"
    .t_left
      .t_credit
        クレジットカード情報入力
      .t_credit_area
        .t_cards
          .t_cards_form
            .t_cards_form__group1
              .t_cards_member
                .t_cards_number
                  カード番号
                .t_cards_hissu
                  必須
              = form_tag('/items/new',method: :post) do
                %input{type: "input",class: "t_cards_input",placeholder: "半角数字のみ"}
              = image_tag("card-1.gif",class: "t_icon_card")
            .t_cards_form__group2
              .t_cards_member
                .t_cards_limit
                  有効期限
                .t_cards_hissu
                  必須
              .t_pulldown
                .t_pulldown_group
                  = form_tag('/items/new',method: :post) do
                    %select(name="example" class="t_pulldown_group__menu")
                      %option 01
                      %option 02
                      %option 03
                      %option 04
                      %option 05
                      %option 06
                      %option 07
                      %option 08
                      %option 09
                      %option 10
                      %option 11
                      %option 12
                  %span(class = "t_span1")  月
                .t_30years_group
                  = form_tag('/items/new',method: :post) do
                    %select(name="example" class="t_pulldown_group__menu")
                      %option 20
                      %option 21
                      %option 22
                      %option 23
                      %option 24
                      %option 25
                      %option 26
                      %option 27
                      %option 28
                      %option 29
                      %option 30
                      %option 31     
                  %span(class = "t_span2")  年
            .t_cards_form__group3
              .t_cards_member
                .t_cards_security
                  セキュリティコード
                .t_cards_hissu
                  必須
              = form_tag('/items/new',method: :post) do
                %input{type: "input",class:"t_cards_member_form",placeholder: "カード背面4桁もしくは3桁の番号"}
            .t_cards_form__group4
              = form_tag('/items/new',method: :post) do
                %input{type: "submit", value: "追加する",class: "t_add_bottun" }

  = render "items/items_toppage_footer"

app/views/cards/show.html.haml
.all
  = render "users/users_header2"
  .h_main
    = render "users/leftbar"
    .h_right
      .h_right__contents
        %h2.h_right__contents__head 支払い方法
        .h_right__contents__main 
          = render "show"
          = form_tag(delete_cards_path, method: :post, id: 'charge-form', name: "inputForm") do
            %input{ type: "hidden", name: "card_id", value: "" }
              %button.h_right__contents__main__btn 削除する
  = render "items/items_toppage_footer"